// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"StampApi/pkg/models/shared"
	"net/http"
)

type CreatePostSecurity struct {
	Jwt string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

type CreatePostResponse struct {
	ContentType string
	// post created
	Post        *shared.Post
	StatusCode  int
	RawResponse *http.Response
}
