// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"StampApi/pkg/models/shared"
	"net/http"
)

type GetRecentPostsRequest struct {
	// Guid of the last fetched item, used to retrive next batch of postings. Empty will return the first page.
	LastFetchedItemID *string `queryParam:"style=form,explode=true,name=lastFetchedItemId"`
	// Number of results are included in a page
	Size *int `queryParam:"style=form,explode=true,name=size"`
}

type GetRecentPostsResponse struct {
	ContentType string
	// successful
	PostResultSet *shared.PostResultSet
	StatusCode    int
	RawResponse   *http.Response
}
