// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"StampApi/pkg/models/shared"
	"net/http"
)

type LogInResponse struct {
	ContentType string
	// login sucessful
	LogInResponse *shared.LogInResponse
	StatusCode    int
	RawResponse   *http.Response
}
