// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"StampApi/pkg/models/shared"
	"net/http"
)

type RefreshTokenSecurity struct {
	Jwt string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

type RefreshTokenResponse struct {
	ContentType string
	// Refresh Sucessful
	RefreshTokenResponse *shared.RefreshTokenResponse
	StatusCode           int
	RawResponse          *http.Response
}
