// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// LogInRequest - request body for signing up and logging in. Specify one of the currently supported authProviders ['github'] and accessToken for the auth provider
type LogInRequest struct {
	AccessToken  string `json:"accessToken"`
	AuthProvider string `json:"authProvider"`
}
