// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// PostResultSet - successful
type PostResultSet struct {
	Count    int    `json:"count"`
	PageSize int    `json:"pageSize"`
	Posts    []Post `json:"posts"`
}
