// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// Post - post created
type Post struct {
	CreatedDate string `json:"createdDate"`
	Description string `json:"description"`
	ID          string `json:"id"`
	Link        string `json:"link"`
	RootDomain  string `json:"rootDomain"`
	Title       string `json:"title"`
}
